// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mhwildsdb.Persistance;

#nullable disable

namespace mhwildsdb.Migrations
{
    [DbContext(typeof(MhwildsDbContext))]
    [Migration("20260509173016_RenamedArmourSkillRanksColumn")]
    partial class RenamedArmourSkillRanksColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.Property<Guid>("ArmoursId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillRanksId")
                        .HasColumnType("uuid");

                    b.HasKey("ArmoursId", "SkillRanksId");

                    b.HasIndex("SkillRanksId");

                    b.ToTable("ArmourSkillRanks", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Piece")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Slots")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("Slots");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Armours", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Skills", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.SkillRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRanks", "app");
                });

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Armour", null)
                        .WithMany()
                        .HasForeignKey("ArmoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armour", b =>
                {
                    b.OwnsOne("mhwildsdb.Entities.Resistances", "Resistances", b1 =>
                        {
                            b1.Property<Guid>("ArmourId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Dragon")
                                .HasColumnType("integer")
                                .HasColumnName("DragonResistance");

                            b1.Property<int>("Fire")
                                .HasColumnType("integer")
                                .HasColumnName("FireResistance");

                            b1.Property<int>("Ice")
                                .HasColumnType("integer")
                                .HasColumnName("IceResistance");

                            b1.Property<int>("Thunder")
                                .HasColumnType("integer")
                                .HasColumnName("ThunderResistance");

                            b1.Property<int>("Water")
                                .HasColumnType("integer")
                                .HasColumnName("WaterResistance");

                            b1.HasKey("ArmourId");

                            b1.ToTable("Armours", "app");

                            b1.WithOwner()
                                .HasForeignKey("ArmourId");
                        });

                    b.Navigation("Resistances")
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.SkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "Skill")
                        .WithMany("Ranks")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.Skill", b =>
                {
                    b.Navigation("Ranks");
                });
#pragma warning restore 612, 618
        }
    }
}
