// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mhwildsdb.Persistance;

#nullable disable

namespace mhwildsdb.Migrations
{
    [DbContext(typeof(MhwildsDbContext))]
    [Migration("20260530144032_AddedWeaponModels")]
    partial class AddedWeaponModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.Property<Guid>("ArmoursId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillRanksId")
                        .HasColumnType("uuid");

                    b.HasKey("ArmoursId", "SkillRanksId");

                    b.HasIndex("SkillRanksId");

                    b.ToTable("ArmourSkillRanks", "app");
                });

            modelBuilder.Entity("CharmRankSkillRank", b =>
                {
                    b.Property<Guid>("CharmRankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uuid")
                        .HasColumnName("SkillRankId");

                    b.HasKey("CharmRankId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CharmRankSkillRanks", "app");
                });

            modelBuilder.Entity("DecorationSkillRank", b =>
                {
                    b.Property<Guid>("DecorationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uuid")
                        .HasColumnName("SkillRanksId");

                    b.HasKey("DecorationId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("DecorationSkillRanks", "app");
                });

            modelBuilder.Entity("SkillRankWeapon", b =>
                {
                    b.Property<Guid>("SkillRanksId")
                        .HasColumnType("uuid")
                        .HasColumnName("SkillRanksId");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("SkillRanksId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponSkillRanks", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.Armour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmourSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Piece")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Slots")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("Slots");

                    b.HasKey("Id");

                    b.HasIndex("ArmourSetId");

                    b.HasIndex("Name");

                    b.ToTable("Armours", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.ArmourSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupBonusSkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SetBonusSkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupBonusSkillId");

                    b.HasIndex("Name");

                    b.HasIndex("SetBonusSkillId");

                    b.ToTable("ArmourSets", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.Charm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Charms", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.CharmRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharmId");

                    b.ToTable("CharmRanks", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Decoration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Decorations", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Skills", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.SkillRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SetPieceRequired")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRanks", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Affinity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Slots")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("Slots");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Weapons", "app");

                    b.HasDiscriminator<string>("WeaponType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.MeleeWeapon", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.Weapon");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.RangedWeapon", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.Weapon");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.DualBlades", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("DualBlades");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Greatsword", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("Greatsword");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Gunlance", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("Gunlance");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Hammer", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("Hammer");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.HuntingHorn", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("HuntingHorn");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.InsectGlaive", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.Property<int>("KinsectLevel")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("InsectGlaive");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Lance", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("Lance");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Longsword", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("Longsword");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.PhialWeapon", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.SwordAndShield", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.MeleeWeapon");

                    b.HasDiscriminator().HasValue("SwordAndShield");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Bow", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.RangedWeapon");

                    b.PrimitiveCollection<int[]>("Coatings")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("Coatings");

                    b.HasDiscriminator().HasValue("Bow");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.HeavyBowgun", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.RangedWeapon");

                    b.HasDiscriminator().HasValue("HeavyBowgun");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.LightBowgun", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.RangedWeapon");

                    b.Property<string>("SpecialAmmo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("LightBowgun");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.ChargeBlade", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.PhialWeapon");

                    b.HasDiscriminator().HasValue("ChargeBlade");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.SwitchAxe", b =>
                {
                    b.HasBaseType("mhwildsdb.Entities.Weapons.PhialWeapon");

                    b.HasDiscriminator().HasValue("SwitchAxe");
                });

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Armours.Armour", null)
                        .WithMany()
                        .HasForeignKey("ArmoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharmRankSkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Charms.CharmRank", null)
                        .WithMany()
                        .HasForeignKey("CharmRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecorationSkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Decoration", null)
                        .WithMany()
                        .HasForeignKey("DecorationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillRankWeapon", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Weapons.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.Armour", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Armours.ArmourSet", "ArmourSet")
                        .WithMany("Pieces")
                        .HasForeignKey("ArmourSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("mhwildsdb.Entities.Resistances", "Resistances", b1 =>
                        {
                            b1.Property<Guid>("ArmourId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Dragon")
                                .HasColumnType("integer")
                                .HasColumnName("DragonResistance");

                            b1.Property<int>("Fire")
                                .HasColumnType("integer")
                                .HasColumnName("FireResistance");

                            b1.Property<int>("Ice")
                                .HasColumnType("integer")
                                .HasColumnName("IceResistance");

                            b1.Property<int>("Thunder")
                                .HasColumnType("integer")
                                .HasColumnName("ThunderResistance");

                            b1.Property<int>("Water")
                                .HasColumnType("integer")
                                .HasColumnName("WaterResistance");

                            b1.HasKey("ArmourId");

                            b1.ToTable("Armours", "app");

                            b1.WithOwner()
                                .HasForeignKey("ArmourId");
                        });

                    b.Navigation("ArmourSet");

                    b.Navigation("Resistances")
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.ArmourSet", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "GroupBonusSkill")
                        .WithMany()
                        .HasForeignKey("GroupBonusSkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "SetBonusSkill")
                        .WithMany()
                        .HasForeignKey("SetBonusSkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GroupBonusSkill");

                    b.Navigation("SetBonusSkill");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.CharmRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Charms.Charm", "Charm")
                        .WithMany("Ranks")
                        .HasForeignKey("CharmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charm");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.SkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "Skill")
                        .WithMany("Ranks")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Weapon", b =>
                {
                    b.OwnsOne("mhwildsdb.Entities.Weapons.Damage", "Damage", b1 =>
                        {
                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Display")
                                .HasColumnType("integer")
                                .HasColumnName("DisplayDamage");

                            b1.Property<int>("Raw")
                                .HasColumnType("integer")
                                .HasColumnName("RawDamage");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Weapons", "app");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.OwnsMany("mhwildsdb.Entities.Weapons.WeaponSpecial", "Specials", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Element")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("Hidden")
                                .HasColumnType("boolean");

                            b1.Property<string>("Status")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WeaponId");

                            b1.ToTable("WeaponSpecials", "app");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");

                            b1.OwnsOne("mhwildsdb.Entities.Weapons.Damage", "Damage", b2 =>
                                {
                                    b2.Property<Guid>("WeaponSpecialId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Display")
                                        .HasColumnType("integer")
                                        .HasColumnName("DisplayDamage");

                                    b2.Property<int>("Raw")
                                        .HasColumnType("integer")
                                        .HasColumnName("RawDamage");

                                    b2.HasKey("WeaponSpecialId");

                                    b2.ToTable("WeaponSpecials", "app");

                                    b2.WithOwner()
                                        .HasForeignKey("WeaponSpecialId");
                                });

                            b1.Navigation("Damage")
                                .IsRequired();
                        });

                    b.Navigation("Damage")
                        .IsRequired();

                    b.Navigation("Specials");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.MeleeWeapon", b =>
                {
                    b.OwnsOne("mhwildsdb.Entities.Weapons.Sharpness", "Sharpness", b1 =>
                        {
                            b1.Property<Guid>("MeleeWeaponId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Blue")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessBlue");

                            b1.Property<int>("Green")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessGreen");

                            b1.Property<int>("Orange")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessOrange");

                            b1.Property<int>("Purple")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessPurple");

                            b1.Property<int>("Red")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessRed");

                            b1.Property<int>("White")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessWhite");

                            b1.Property<int>("Yellow")
                                .HasColumnType("integer")
                                .HasColumnName("SharpnessYellow");

                            b1.HasKey("MeleeWeaponId");

                            b1.ToTable("Weapons", "app");

                            b1.WithOwner()
                                .HasForeignKey("MeleeWeaponId");
                        });

                    b.Navigation("Sharpness")
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.RangedWeapon", b =>
                {
                    b.OwnsMany("mhwildsdb.Entities.Weapons.Ammo", "Ammo", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<bool?>("Rapid")
                                .HasColumnType("boolean");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WeaponId");

                            b1.ToTable("WeaponAmmo", "app");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.Navigation("Ammo");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.Gunlance", b =>
                {
                    b.OwnsOne("mhwildsdb.Entities.Weapons.Shell", "Shell", b1 =>
                        {
                            b1.Property<Guid>("GunlanceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Power")
                                .HasColumnType("integer")
                                .HasColumnName("ShellPower");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("ShellType");

                            b1.HasKey("GunlanceId");

                            b1.ToTable("Weapons", "app");

                            b1.WithOwner()
                                .HasForeignKey("GunlanceId");
                        });

                    b.Navigation("Shell")
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Weapons.PhialWeapon", b =>
                {
                    b.OwnsOne("mhwildsdb.Entities.Weapons.Phial", "Phial", b1 =>
                        {
                            b1.Property<Guid>("PhialWeaponId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("PhialType");

                            b1.HasKey("PhialWeaponId");

                            b1.ToTable("Weapons", "app");

                            b1.WithOwner()
                                .HasForeignKey("PhialWeaponId");

                            b1.OwnsOne("mhwildsdb.Entities.Weapons.Damage", "Damage", b2 =>
                                {
                                    b2.Property<Guid>("PhialWeaponId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Display")
                                        .HasColumnType("integer")
                                        .HasColumnName("PhialDisplayDamage");

                                    b2.Property<int>("Raw")
                                        .HasColumnType("integer")
                                        .HasColumnName("PhialRawDamage");

                                    b2.HasKey("PhialWeaponId");

                                    b2.ToTable("Weapons", "app");

                                    b2.WithOwner()
                                        .HasForeignKey("PhialWeaponId");
                                });

                            b1.Navigation("Damage");
                        });

                    b.Navigation("Phial")
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.ArmourSet", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.Charm", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.Skill", b =>
                {
                    b.Navigation("Ranks");
                });
#pragma warning restore 612, 618
        }
    }
}
