// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mhwildsdb.Persistance;

#nullable disable

namespace mhwildsdb.Migrations
{
    [DbContext(typeof(MhwildsDbContext))]
    [Migration("20260525143210_IncreasedArmourRankColumnLength")]
    partial class IncreasedArmourRankColumnLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.Property<Guid>("ArmoursId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillRanksId")
                        .HasColumnType("uuid");

                    b.HasKey("ArmoursId", "SkillRanksId");

                    b.HasIndex("SkillRanksId");

                    b.ToTable("ArmourSkillRanks", "app");
                });

            modelBuilder.Entity("CharmRankSkillRank", b =>
                {
                    b.Property<Guid>("CharmRankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uuid")
                        .HasColumnName("SkillRankId");

                    b.HasKey("CharmRankId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CharmRankSkillRanks", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.Armour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmourSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Piece")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Slots")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("Slots");

                    b.HasKey("Id");

                    b.HasIndex("ArmourSetId");

                    b.HasIndex("Name");

                    b.ToTable("Armours", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.ArmourSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupBonusSkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SetBonusSkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupBonusSkillId");

                    b.HasIndex("Name");

                    b.HasIndex("SetBonusSkillId");

                    b.ToTable("ArmourSets", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.Charm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Charms", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.CharmRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharmId");

                    b.ToTable("CharmRanks", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Skills", "app");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.SkillRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SetPieceRequired")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRanks", "app");
                });

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Armours.Armour", null)
                        .WithMany()
                        .HasForeignKey("ArmoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharmRankSkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Charms.CharmRank", null)
                        .WithMany()
                        .HasForeignKey("CharmRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwildsdb.Entities.Skills.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.Armour", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Armours.ArmourSet", "ArmourSet")
                        .WithMany("Pieces")
                        .HasForeignKey("ArmourSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("mhwildsdb.Entities.Resistances", "Resistances", b1 =>
                        {
                            b1.Property<Guid>("ArmourId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Dragon")
                                .HasColumnType("integer")
                                .HasColumnName("DragonResistance");

                            b1.Property<int>("Fire")
                                .HasColumnType("integer")
                                .HasColumnName("FireResistance");

                            b1.Property<int>("Ice")
                                .HasColumnType("integer")
                                .HasColumnName("IceResistance");

                            b1.Property<int>("Thunder")
                                .HasColumnType("integer")
                                .HasColumnName("ThunderResistance");

                            b1.Property<int>("Water")
                                .HasColumnType("integer")
                                .HasColumnName("WaterResistance");

                            b1.HasKey("ArmourId");

                            b1.ToTable("Armours", "app");

                            b1.WithOwner()
                                .HasForeignKey("ArmourId");
                        });

                    b.Navigation("ArmourSet");

                    b.Navigation("Resistances")
                        .IsRequired();
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.ArmourSet", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "GroupBonusSkill")
                        .WithMany()
                        .HasForeignKey("GroupBonusSkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "SetBonusSkill")
                        .WithMany()
                        .HasForeignKey("SetBonusSkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GroupBonusSkill");

                    b.Navigation("SetBonusSkill");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.CharmRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Charms.Charm", "Charm")
                        .WithMany("Ranks")
                        .HasForeignKey("CharmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charm");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.SkillRank", b =>
                {
                    b.HasOne("mhwildsdb.Entities.Skills.Skill", "Skill")
                        .WithMany("Ranks")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Armours.ArmourSet", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Charms.Charm", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("mhwildsdb.Entities.Skills.Skill", b =>
                {
                    b.Navigation("Ranks");
                });
#pragma warning restore 612, 618
        }
    }
}
